# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Work in Progress
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Work in Progress is a daily live show about product management - shipping, working with teams, making design decisions, debating what makes it into a product, knowing when to throw something away, etc. It's all current - stuff Nathan and I are struggling with on a daily basis. Sometimes we'll show work in progress and critique each other's work and ideas. Each show lasts about 30 minutes, so join in, subscribe to the channel, and hopefully learn a thing or two.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://workinprogress.show" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Handling Reading
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "Guardfile"
  - "bin/"
  - "script/"
  - "README.md"

# GitHub Pages Defaults
# (Ref.: https://help.github.com/articles/using-jekyll-with-pages/#defaults)
# highlighter: pygments
# github: [Repository metadata]

# GitHub Pages Overrides (you cannot change this)
# (Ref.: https://help.github.com/articles/using-jekyll-with-pages/#configuration-overrides)
# safe: true
# lsi: false
# source: your top-level directory

# Jekyll Plugins with GitHub Pages
# (Ref.: https://help.github.com/articles/using-jekyll-plugins-with-github-pages/)
gems:
- jekyll-sitemap
# - jekyll-feed
- jekyll-redirect-from
- jemoji

# Custom settings
custom:
  ext:
    rawgit:
      url: "https://cdn.rawgit.com/workinprogress/website-assets"
    youtube:
      url: "https://www.youtube.com/watch?v="
